version: "3.8"

services:
  frontend:
    build: ./frontend
    command: npm run dev -- --host --port 5173
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  backend:
    build: ./backend
    command: npm run dev
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - uploads_data:/app/uploads
    env_file:
      - ./.env
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - mongodb
  redis:
    image: redis
    ports:
      - "6379:6379"

  python:
    build: ./python
    container_name: python
    ports:
      - "8000:8000"
    volumes:
      - uploads_data:/app/uploads
    env_file:
      - ./.env
    depends_on:
      - backend
      - frontend
      - redis
      - mongodb

  mongodb:
    image: mongo:latest
    env_file:
      - ./.env
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
  uploads_data:
