version: '3.8'

services:
  frontend:
    build: ./frontend
    command: npm run dev -- --host --port 5173
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  backend:
    build: ./backend
    command: npx nodemon server.js
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./.env
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    env_file:
      - ./.env
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
